# Generated by Django 5.0.6 on 2024-07-10 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Intersection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("intersection_id", models.CharField(max_length=50, unique=True)),
                ("coordinates", models.CharField(max_length=100)),
                ("condition", models.CharField(default="Live", max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="ScoreRating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("points", models.IntegerField(default=120)),
            ],
        ),
        migrations.CreateModel(
            name="Safety",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("accident_rate", models.IntegerField(default=0)),
                ("near_misses", models.IntegerField(default=0)),
                ("speeding", models.IntegerField(default=0)),
                ("traffic_violations", models.IntegerField(default=0)),
                ("pedestrian_incidents", models.IntegerField(default=0)),
                ("damaged_disabled_vehicle", models.IntegerField(default=0)),
                (
                    "intersection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="safety_scores",
                        to="atlas_trafic_app.intersection",
                    ),
                ),
                (
                    "score_rating",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="safety",
                        to="atlas_trafic_app.scorerating",
                    ),
                ),
            ],
        ),
    ]
