# Generated by Django 5.0.6 on 2024-07-11 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("atlas_trafic_app", "0002_alter_scorerating_points"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="safety",
            name="score_rating",
        ),
        migrations.AddField(
            model_name="safety",
            name="points",
            field=models.FloatField(default=120),
        ),
        migrations.DeleteModel(
            name="ScoreRating",
        ),
    ]
