# Generated by Django 5.0.6 on 2024-07-15 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("atlas_trafic_app", "0003_remove_safety_score_rating_safety_points_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="safety",
            name="accident_rate",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="safety",
            name="damaged_disabled_vehicle",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="safety",
            name="near_misses",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="safety",
            name="pedestrian_incidents",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="safety",
            name="speeding",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="safety",
            name="traffic_violations",
            field=models.FloatField(default=0),
        ),
        migrations.CreateModel(
            name="Efficiency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("points", models.FloatField(default=120)),
                ("congestion_level", models.FloatField(default=0)),
                ("average_traffic_speed", models.FloatField(default=0)),
                ("traffic_volume", models.FloatField(default=0)),
                ("signal_timing_efficiency", models.FloatField(default=0)),
                ("pedestrian_wait_time", models.FloatField(default=0)),
                ("micro_mobility_wait_time", models.FloatField(default=0)),
                (
                    "intersection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="efficiency_scores",
                        to="atlas_trafic_app.intersection",
                    ),
                ),
            ],
        ),
    ]
