# Generated by Django 5.0.6 on 2024-07-16 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("atlas_trafic_app", "0004_alter_safety_accident_rate_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Environmental",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("points", models.FloatField(default=120)),
                ("vehicle_emissions", models.FloatField(default=0)),
                ("fuel_consumption", models.FloatField(default=0)),
                ("noise_pollution", models.FloatField(default=0)),
                ("air_quality_index", models.FloatField(default=0)),
                ("driving_conditions", models.FloatField(default=0)),
                ("fire_detection", models.BooleanField(default=False)),
                (
                    "intersection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="environmental_scores",
                        to="atlas_trafic_app.intersection",
                    ),
                ),
            ],
        ),
    ]
