# Generated by Django 5.0.6 on 2024-06-26 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_user_otp_user_otp_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="question_1",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="question_2",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="question_3",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
