# Generated by Django 5.0.6 on 2024-06-26 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_user_question_1_user_question_2_user_question_3"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="question_1",
            new_name="answer_1",
        ),
        migrations.RenameField(
            model_name="user",
            old_name="question_2",
            new_name="answer_2",
        ),
        migrations.RenameField(
            model_name="user",
            old_name="question_3",
            new_name="answer_3",
        ),
    ]
